services:
  projectname:
    container_name: projectname-compose
    build: .
    depends_on:
      - postgres-18
    env_file:
      - .env.docker-compose
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 300s
      retries: 30
      start_period: 5s
    image: projectname:latest
    networks:
      - projectname-network
    ports:
      - 8080:8000
    volumes:
      - projectname-configs-volume:/etc/projectname
  postgres-18:
    container_name: projectname-postgres-18-compose
    env_file:
      - .env.docker-compose
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 300s
      retries: 30
      start_period: 5s
    image: postgres:18
    networks:
      - projectname-network
    volumes:
      - postgres-18-volume:/var/lib/postgresql
networks:
  projectname-network:
    name: projectname-compose-network
    driver: bridge
volumes:
  projectname-configs-volume:
    name: projectname-configs-compose-volume
  postgres-18-volume:
    name: projectname-postgres-18-data-compose-volume
