services:
  projectname-dev:
    container_name: projectname-dev-compose-instance
    command: dev
    depends_on:
      - postgres-18
    env_file:
      - .env.d/.env.dev
    environment:
      - PROJECTNAME_DATABASE_HOST=postgres-18
      - PROJECTNAME_DATABASE_PORT=5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 300s
      retries: 30
      start_period: 5s
    image: projectname:${DOCKER_TAG}
    networks:
      - projectname-dev-network
    ports:
      - 8080:8000
    volumes:
      - projectname-dev-configs-volume:/etc/projectname-dev
  postgres-18:
    container_name: projectname-dev-postgres-18-compose-instance
    env_file:
      - .env.d/.env.dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 300s
      retries: 30
      start_period: 5s
    image: postgres:18
    networks:
      - projectname-dev-network
    volumes:
      - postgres-18-volume:/var/lib/postgresql
networks:
  projectname-dev-network:
    name: projectname-dev-compose-network
    driver: bridge
volumes:
  projectname-dev-configs-volume:
    name: projectname-dev-configs-compose-volume
  postgres-18-volume:
    name: projectname-dev-postgres-18-data-compose-volume
