services:
  projectname-test:
    container_name: projectname-test-compose-instance
    depends_on:
      - postgres-18
    env_file:
      - .env.d/.env.test
    environment:
      - PROJECTNAME_DATABASE_HOST=postgres-18
      - PROJECTNAME_DATABASE_PORT=5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 300s
      retries: 30
      start_period: 5s
    image: projectname:${DOCKER_TAG}
    networks:
      - projectname-test-network
    ports:
      - 8080:8000
    volumes:
      - projectname-test-configs-volume:/etc/projectname-test
  postgres-18:
    container_name: projectname-test-postgres-18-compose-instance
    env_file:
      - .env.d/.env.test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 300s
      retries: 30
      start_period: 5s
    image: postgres:18
    networks:
      - projectname-test-network
    volumes:
      - postgres-18-volume:/var/lib/postgresql
networks:
  projectname-test-network:
    name: projectname-test-compose-network
    driver: bridge
volumes:
  projectname-test-configs-volume:
    name: projectname-test-configs-compose-volume
  postgres-18-volume:
    name: projectname-test-postgres-18-data-compose-volume
