services:
  foo-project-name:
    container_name: foo-project-name-compose-instance
    depends_on:
      - postgres-18
    env_file:
      - ../.env
    environment:
      - FOO_PROJECT_NAME_DATABASE_HOST=postgres-18
      - FOO_PROJECT_NAME_DATABASE_PORT=5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 300s
      retries: 30
      start_period: 5s
    image: foo-project-name:${docker_image_tag}
    networks:
      - foo-project-name-network
    ports:
      - 8080:8000
    volumes:
      - foo-project-name-configs-volume:/etc/foo-project-name
  postgres-18:
    container_name: foo-project-name-postgres-18-compose-instance
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 300s
      retries: 30
      start_period: 5s
    image: postgres:18
    networks:
      - foo-project-name-network
    volumes:
      - postgres-18-volume:/var/lib/postgresql
networks:
  foo-project-name-network:
    name: foo-project-name-compose-network
    driver: bridge
volumes:
  foo-project-name-configs-volume:
    name: foo-project-name-configs-compose-volume
  postgres-18-volume:
    name: foo-project-name-postgres-18-data-compose-volume
