services:
  foo_project_name:
    container_name: foo_project_name
    depends_on:
      - postgres-18
    env_file:
      - ../.env
    environment:
      - FOO_PROJECT_NAME_DATABASE_HOST=postgres-18
      - FOO_PROJECT_NAME_DATABASE_PORT=5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 300s
      retries: 30
      start_period: 5s
    image: foo_project_name:${docker_image_tag}
    networks:
      - foo_project_name_network
    ports:
      - 8080:8000
    volumes:
      - foo_project_name_configs:/etc/foo_project_name
  postgres-18:
    container_name: foo_project_name_postgres_18
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 300s
      retries: 30
      start_period: 5s
    image: postgres:18
    networks:
      - foo_project_name_network
    volumes:
      - postgres-18-volume:/var/lib/postgresql
networks:
  foo_project_name_network:
    name: foo_project_name_network
    driver: bridge
volumes:
  foo_project_name_configs:
    name: foo_project_name_configs
  postgres-18-volume:
    name: foo_project_name_postgres_18_data
