name: Linters and unit tests
on:
  workflow_call:
jobs:
  linters-and-unit-tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/env-setup-dev
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      - uses: ./.github/actions/run-linters