name: Linters and unit tests
on:
  workflow_call:
jobs:
  linters-and-unit-tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/import-flow-check
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      - uses: ./.github/actions/unused-classes-check
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      - uses: ./.github/actions/pythonic-linters
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      - uses: ./.github/actions/unit-tests
        with:
          python-version: ${{ vars.PYTHON_VERSION }}