name: Entrypoint
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  linters-and-unit-tests:
    uses: ./.github/workflows/linters-and-unit-tests.yml
  api:
    uses: ./.github/workflows/api.yml
